import { Inter } from "next/font/google";
import "./globals.css";
import { PostProvider } from './context/PostContext';
import { CookiesProvider } from "next-client-cookies/server";
import { RolProvider } from "./context/RolContext";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <PostProvider>
            <RolProvider>
              <CookiesProvider>
                {children}
              </CookiesProvider>
            </RolProvider>
          </PostProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
